language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t graneng/trying-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true graneng/trying-docker npm run test -- --coverage
